# Site settings
title: TechAachen
title_meta: "TechAachen — Technische studentische Vereine Aachen"
author: TechAachen e.V.
email: info@techaachen.de
description: |
  TechAachen: Zusammenschluss technischer Vereine in Aachen.
  Wir erarbeiten & lehren Wissen, entwickeln Ideen, bestreiten Wettkämpfe und fördern Nachhaltigkeit.

keywords: |
  TechAachen, Aachen, Student, Eigeninitiative, Verein,
  Technik, Wissen, Bildung, Forschung, Wissenschaft,
  RWTH, FH, Uni, Universität,
  Wettbewerb, Wettkampf, Nachhaltigkeit, Ideen, Förderung,
  Ecurie Aix, Enactus, Flugwissenschaftliche Vereinigung, Mx Aix, Roboterclub, Sonnenwagen, Studiwerkstatt, Windfänger

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

contact_twitter_username: techaachen
contact_facebook_username: techaachen
contact_instagram_username: techaachen
contact_address: "TechAachen e.V.<br /> Templergraben 55 <br /> 52056 Aachen"

# Build settings
markdown: kramdown

plugins:
  - jekyll-minifier
  - jekyll-paginate
  - jekyll-assets
  - jekyll-bootstrap-sass
  - jekyll-font-awesome-sass

assets:
  digest: true
  prefix: "/assets"
  sources:
    - "_assets/css"
    - "_assets/js"
  compress:
    css: sass
    js: uglifier
  source_maps: false

bootstrap:
  assets: true

font-awesome:
  assets: true
