# Site settings
title: TechAachen
title_meta: "TechAachen — Technische studentische Vereine Aachen"
author: TechAachen e.V.
email: info@techaachen.de
telefon: +49 176 66889668

description: |
  TechAachen: Zusammenschluss technischer Vereine in Aachen.
  Wir erarbeiten & lehren Wissen, entwickeln Ideen, bestreiten Wettkämpfe und fördern Nachhaltigkeit.

slogan: Gemeinsam Träume verwirklichen.

keywords: |
  TechAachen, Aachen, Student, Eigeninitiative, Verein,
  Technik, Wissen, Bildung, Forschung, Wissenschaft,
  RWTH, FH, Uni, Universität,
  Wettbewerb, Wettkampf, Nachhaltigkeit, Ideen, Förderung,
  Ecurie Aix, Enactus, Flugwissenschaftliche Vereinigung, Mx Aix, Roboterclub, Sonnenwagen, Studiwerkstatt, Windfänger

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

contact_twitter_username: techaachen
contact_facebook_username: techaachen
contact_instagram_username: techaachen
contact_address: "TechAachen e.V.<br /> c.o. FVA <br /> Templergraben 55 <br /> 52056 Aachen"

# Build settings
markdown: kramdown

plugins:
  - jekyll-bootstrap-sass
#  - jekyll-font-awesome-sass

sass:
  style: compressed
  sass_dir: _sass

font-awesome:
  assets: true
