FROM ubuntu:22.04
LABEL maintainer="Raphael Lehmann <raphael+docker@rleh.de>"
LABEL description="Jekyll Pfusch image"

WORKDIR /work

ADD Gemfile /work

ENV LANG="en_US.UTF-8"
ENV TZ=Europe/Berlin
ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq && \
    apt-get upgrade -y -qq && \
    apt-get install -y -qq \
      ruby-full \
      rubygems \
      libffi-dev \
      build-essential && \
    apt-get clean -qq
RUN gem install jekyll bundler
RUN bundle install
